const flags = [
  "flags/medium/afghanistan.png",
  "flags/hard/aland islands.png",
  "flags/medium/albania.png",
  "flags/medium/algeria.png",
  "flags/hard/american samoa.png",
  "flags/hard/andorra.png",
  "flags/hard/angola.png",
  "flags/hard/anguilla.png",
  "flags/hard/antigua and barbuda.png",
  "flags/easy/argentina.png",
  "flags/medium/armenia.png",
  "flags/hard/aruba.png",
  "flags/easy/australia.png",
  "flags/easy/austria.png",
  "flags/medium/azerbaijan.png",
  "flags/medium/bahamas.png",
  "flags/medium/bahrain.png",
  "flags/medium/bangladesh.png",
  "flags/medium/barbados.png",
  "flags/medium/belarus.png",
  "flags/easy/belgium.png",
  "flags/hard/belize.png",
  "flags/medium/benin.png",
  "flags/hard/bermuda.png",
  "flags/medium/bhutan.png",
  "flags/medium/bolivia.png",
  "flags/medium/bosnia and herzegovina.png",
  "flags/medium/botswana.png",
  "flags/easy/brazil.png",
  "flags/hard/british indian ocean territory.png",
  "flags/hard/british virgin islands.png",
  "flags/hard/brunei.png",
  "flags/medium/bulgaria.png",
  "flags/medium/burkina faso.png",
  "flags/hard/burundi.png",
  "flags/medium/cambodia.png",
  "flags/easy/cameroon.png",
  "flags/easy/canada.png",
  "flags/hard/cape verde.png",
  "flags/hard/cayman islands.png",
  "flags/hard/central african republic.png",
  "flags/medium/chad.png",
  "flags/medium/chile.png",
  "flags/easy/china.png",
  "flags/hard/christmas island.png",
  "flags/hard/cocos islands.png",
  "flags/easy/colombia.png",
  "flags/medium/comoros.png",
  "flags/hard/cook islands.png",
  "flags/medium/costa rica.png",
  "flags/easy/croatia.png",
  "flags/medium/cuba.png",
  "flags/hard/curucao.png",
  "flags/medium/cyprus.png",
  "flags/medium/czech republic.png",
  "flags/easy/denmark.png",
  "flags/hard/djibouti.png",
  "flags/hard/dominica.png",
  "flags/medium/dominican republic.png",
  "flags/easy/ecuador.png",
  "flags/easy/egypt.png",
  "flags/medium/el salvador.png",
  "flags/easy/england.png",
  "flags/medium/equatorial guinea.png",
  "flags/medium/eritrea.png",
  "flags/medium/estonia.png",
  "flags/hard/eswatini.png",
  "flags/hard/ethiopia.png",
  "flags/hard/falkland islands.png",
  "flags/hard/faroe islands.png",
  "flags/hard/fiji.png",
  "flags/easy/finland.png",
  "flags/easy/france.png",
  "flags/hard/french guiana.png",
  "flags/hard/french polynesia.png",
  "flags/hard/french southern and antarctic lands.png",
  "flags/medium/gabon.png",
  "flags/hard/gambia.png",
  "flags/medium/georgia.png",
  "flags/easy/germany.png",
  "flags/medium/ghana.png",
  "flags/hard/gibraltar.png",
  "flags/easy/greece.png",
  "flags/medium/greenland.png",
  "flags/hard/grenada.png",
  "flags/hard/guadeloupe.png",
  "flags/hard/guam.png",
  "flags/medium/guatemala.png",
  "flags/hard/guernsey.png",
  "flags/medium/guinea-bissau.png",
  "flags/hard/guinea.png",
  "flags/hard/guyana.png",
  "flags/hard/haiti.png",
  "flags/hard/heard and mcdonald islands.png",
  "flags/medium/honduras.png",
  "flags/hard/hong kong.png",
  "flags/medium/hungary.png",
  "flags/easy/iceland.png",
  "flags/easy/india.png",
  "flags/medium/indonesia.png",
  "flags/medium/iran.png",
  "flags/medium/iraq.png",
  "flags/easy/ireland.png",
  "flags/hard/isle of man.png",
  "flags/easy/italy.png",
  "flags/easy/jamaica.png",
  "flags/easy/japan.png",
  "flags/hard/jersey.png",
  "flags/medium/jordan.png",
  "flags/medium/kazakhstan.png",
  "flags/medium/kenya.png",
  "flags/hard/kiribati.png",
  "flags/hard/kosovo.png",
  "flags/medium/kuwait.png",
  "flags/hard/kyrgyzstan.png",
  "flags/medium/laos.png",
  "flags/medium/latvia.png",
  "flags/easy/lebanon.png",
  "flags/hard/lesotho.png",
  "flags/medium/liberia.png",
  "flags/medium/libya.png",
  "flags/medium/liechtenstein.png",
  "flags/medium/lithuania.png",
  "flags/medium/luxembourg.png",
  "flags/hard/macao.png",
  "flags/hard/madagascar.png",
  "flags/hard/malawi.png",
  "flags/medium/malaysia.png",
  "flags/hard/maldives.png",
  "flags/medium/mali.png",
  "flags/medium/malta.png",
  "flags/hard/marshall islands.png",
  "flags/hard/martinique.png",
  "flags/medium/mauritania.png",
  "flags/hard/mauritius.png",
  "flags/hard/mayotte.png",
  "flags/easy/mexico.png",
  "flags/hard/micronesia.png",
  "flags/medium/moldova.png",
  "flags/medium/monaco.png",
  "flags/medium/mongolia.png",
  "flags/medium/montenegro.png",
  "flags/hard/montserrat.png",
  "flags/easy/morocco.png",
  "flags/hard/mozambique.png",
  "flags/medium/myanmar.png",
  "flags/hard/namibia.png",
  "flags/hard/nauru.png",
  "flags/medium/nepal.png",
  "flags/easy/netherlands.png",
  "flags/hard/new caledonia.png",
  "flags/medium/new zealand.png",
  "flags/medium/nicaragua.png",
  "flags/medium/niger.png",
  "flags/easy/nigeria.png",
  "flags/hard/niue.png",
  "flags/hard/norfolk island.png",
  "flags/easy/north korea.png",
  "flags/medium/north macedonia.png",
  "flags/hard/northern mariana islands.png",
  "flags/easy/norway.png",
  "flags/medium/oman.png",
  "flags/easy/pakistan.png",
  "flags/hard/palau.png",
  "flags/medium/palestine.png",
  "flags/medium/panama.png",
  "flags/medium/papua new guinea.png",
  "flags/medium/paraguay.png",
  "flags/medium/peru.png",
  "flags/medium/philippines.png",
  "flags/hard/pitcairn islands.png",
  "flags/easy/poland.png",
  "flags/easy/portugal.png",
  "flags/medium/puerto rico.png",
  "flags/medium/qatar.png",
  "flags/medium/republic of the congo.png",
  "flags/hard/reunion.png",
  "flags/medium/romania.png",
  "flags/easy/russia.png",
  "flags/medium/rwanda.png",
  "flags/hard/saint barthelemy.png",
  "flags/hard/saint helena.png",
  "flags/hard/saint kitts and nevis.png",
  "flags/hard/saint lucia.png",
  "flags/hard/saint pierre and miquelon.png",
  "flags/hard/saint vincent and the grenadines.png",
  "flags/hard/samoa.png",
  "flags/medium/san marino.png",
  "flags/hard/sao tome and principe.png",
  "flags/easy/saudi arabia.png",
  "flags/easy/scotland.png",
  "flags/medium/senegal.png",
  "flags/medium/serbia.png",
  "flags/hard/seychelles.png",
  "flags/medium/sierra leone.png",
  "flags/easy/singapore.png",
  "flags/hard/sint maarten.png",
  "flags/medium/slovakia.png",
  "flags/medium/slovenia.png",
  "flags/hard/solomon islands.png",
  "flags/medium/somalia.png",
  "flags/easy/south africa.png",
  "flags/hard/south georgia and the south sandwich islands.png",
  "flags/easy/south korea.png",
  "flags/medium/south sudan.png",
  "flags/easy/spain.png",
  "flags/medium/sri lanka.png",
  "flags/medium/sudan.png",
  "flags/hard/suriname.png",
  "flags/easy/sweden.png",
  "flags/easy/switzerland.png",
  "flags/easy/syria.png",
  "flags/medium/taiwan.png",
  "flags/medium/tajikistan.png",
  "flags/hard/tanzania.png",
  "flags/medium/thailand.png",
  "flags/medium/timor-leste.png",
  "flags/medium/togo.png",
  "flags/hard/tokelau.png",
  "flags/hard/tonga.png",
  "flags/hard/trinidad and tobago.png",
  "flags/easy/tunisia.png",
  "flags/easy/turkey.png",
  "flags/medium/turkmenistan.png",
  "flags/hard/turks and caicos islands.png",
  "flags/hard/tuvalu.png",
  "flags/medium/uganda.png",
  "flags/easy/ukraine.png",
  "flags/medium/united arab emirates.png",
  "flags/easy/united kingdom.png",
  "flags/hard/united states virgin islands.png",
  "flags/easy/united states.png",
  "flags/easy/uruguay.png",
  "flags/hard/uzbekistan.png",
  "flags/hard/vanuatu.png",
  "flags/medium/vatican city.png",
  "flags/medium/venezuela.png",
  "flags/medium/vietnam.png",
  "flags/medium/wales.png",
  "flags/hard/wallis and futuna.png",
  "flags/medium/western sahara.png",
  "flags/medium/yemen.png",
  "flags/hard/zambia.png",
  "flags/medium/zimbabwe.png",
];

var allEasyFlags = flags.filter(flag => flag.includes("easy"));
var allMediumFlags = flags.filter(flag => flag.includes("medium"));
var allHardFlags = flags.filter(flag => flag.includes("hard"));